/*
 * generated by Xtext
 */
package at.bachmann.plc.st.validation

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class STLanguageValidator extends AbstractSTLanguageValidator {	
}
