/*
* generated by Xtext
*/
package at.bachmann.plc.st.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import at.bachmann.plc.st.services.STLanguageGrammarAccess;

public class STLanguageParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private STLanguageGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_COMMENT", "RULE_WS", "RULE_PRAGMA");
	}
	
	@Override
	protected at.bachmann.plc.st.parser.antlr.internal.InternalSTLanguageParser createParser(XtextTokenStream stream) {
		return new at.bachmann.plc.st.parser.antlr.internal.InternalSTLanguageParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "test";
	}
	
	public STLanguageGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(STLanguageGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
