/*
* generated by Xtext
*/
package at.bachmann.plc.st;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class STLanguageUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return at.bachmann.plc.st.ui.internal.STLanguageActivator.getInstance().getInjector("at.bachmann.plc.st.STLanguage");
	}
	
}
