/*
 * generated by Xtext
 */
package at.bachmann.plc.st;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class STLanguageRuntimeModule extends at.bachmann.plc.st.AbstractSTLanguageRuntimeModule {

}
